import {
  BODY_MEDIA_TYPE,
  effectiveBody,
  participantById,
  type Contract,
  type SequenceDoc,
  type Transport,
} from '../dsl/ast'
import { schemaRef, type JsonSchema } from './jsonSchema'
import { schemaComponents } from './jsonSchema'
import { usedContracts } from './toOpenApi'

const ASYNC_TRANSPORTS = new Set<Transport>([
  'sqs',
  'sns',
  'eventbridge',
  'kinesis',
  'generic-async',
])

const PROTOCOL: Record<string, string> = {
  sqs: 'sqs',
  sns: 'sns',
  eventbridge: 'events',
  kinesis: 'kinesis',
  'generic-async': 'generic',
}

/**
 * One channel per async contract that is actually attached to a message.
 * Unhappy responses become documented `x-seqflow-failure-modes` on the channel
 * so the DLQ / retry story survives the export.
 */
export function toAsyncApi(doc: SequenceDoc, title = 'SeqFlow Events'): string {
  const used = usedContracts(doc).filter((c) => ASYNC_TRANSPORTS.has(c.transport))
  const allSchemas = schemaComponents(doc)

  const channels: Record<string, unknown> = {}
  const messages: Record<string, unknown> = {}
  const schemas: Record<string, JsonSchema> = {}

  for (const contract of used) {
    const carriers = doc.messages.filter((m) => m.contractRef === contract.name)
    const channelName = channelFor(doc, contract, carriers[0]?.to)
    const messageName = `${contract.name}Message`

    if (contract.modelName && allSchemas[contract.modelName]) {
      schemas[contract.modelName] = allSchemas[contract.modelName]
    }
    for (const r of contract.responses) {
      if (r.modelName && allSchemas[r.modelName]) schemas[r.modelName] = allSchemas[r.modelName]
    }

    const kind = effectiveBody(contract)
    const payload = schemaRef(doc, contract.modelName) ?? { type: 'object' }
    messages[messageName] = {
      name: messageName,
      title: contract.name,
      contentType: kind === 'none' ? 'application/json' : BODY_MEDIA_TYPE[kind],
      payload,
      ...(contract.headers.length
        ? {
            headers: {
              type: 'object',
              properties: Object.fromEntries(
                contract.headers.map((h) => [
                  h.key,
                  { type: 'string', description: h.value || undefined },
                ]),
              ),
              required: contract.headers.filter((h) => h.required).map((h) => h.key),
            },
          }
        : {}),
    }

    const failures = contract.responses
      .filter((r) => !r.isHappyPath)
      .map((r) => ({ code: r.code, description: r.label || r.code }))

    channels[channelName] = {
      description: carriers.length
        ? `${carriers[0].from} → ${carriers[0].to}: ${carriers[0].label}`
        : contract.name,
      publish: {
        operationId: `publish${contract.name}`,
        summary: `Publish to ${channelName}`,
        message: { $ref: `#/components/messages/${messageName}` },
      },
      subscribe: {
        operationId: `consume${contract.name}`,
        summary: `Consume from ${channelName}`,
        message: { $ref: `#/components/messages/${messageName}` },
      },
      bindings: { [PROTOCOL[contract.transport] ?? 'generic']: {} },
      ...(failures.length ? { 'x-seqflow-failure-modes': failures } : {}),
    }
  }

  const spec = {
    asyncapi: '2.6.0',
    info: {
      title,
      version: '1.0.0',
      description:
        'Generated by SeqFlow from the async contracts attached to this sequence diagram. Documentation scaffolding, not a validated event definition.',
    },
    ...(used.length
      ? {
          servers: {
            aws: {
              url: 'arn:aws:{region}:{account}',
              protocol: PROTOCOL[used[0].transport] ?? 'generic',
              description: 'Placeholder — point this at your real broker.',
            },
          },
        }
      : {}),
    channels,
    components: { messages, schemas },
  }

  return JSON.stringify(spec, null, 2) + '\n'
}

function channelFor(
  doc: SequenceDoc,
  contract: Contract,
  targetId: string | undefined,
): string {
  const target = targetId ? participantById(doc, targetId) : undefined
  if (target) return target.label.replace(/\s+/g, '')
  return contract.path?.replace(/^\//, '') || contract.name
}
