import {
  BODY_MEDIA_TYPE,
  contractByName,
  effectiveBody,
  isStructuredBody,
  type BodyKind,
  type Contract,
  type SequenceDoc,
} from '../dsl/ast'
import { STATUS_BY_CODE } from '../contracts/unhappyPathRules'
import { schemaComponents, schemaRef, type JsonSchema } from './jsonSchema'

/**
 * One path + method + response entry per HTTP contract that is actually
 * attached to a message. Happy and unhappy responses both appear. A diagram
 * with no contracts yields a valid, near-empty spec rather than an error.
 */
export function toOpenApi(doc: SequenceDoc, title = 'SeqFlow API'): string {
  const used = usedContracts(doc).filter((c) => c.transport === 'http')

  const paths: Record<string, Record<string, unknown>> = {}

  for (const contract of used) {
    const path = contract.path || `/${contract.name}`
    const method = (contract.method ?? 'POST').toLowerCase()
    paths[path] ??= {}

    const parameters = contract.headers.map((h) => ({
      name: h.key,
      in: 'header',
      required: h.required,
      description: h.value || undefined,
      schema: { type: 'string' },
      example: h.value && h.value !== 'string' ? h.value : undefined,
    }))

    const responses: Record<string, unknown> = {}
    const nonHttp: { code: string; label: string }[] = []

    for (const r of contract.responses) {
      if (!/^\d{3}$/.test(r.code)) {
        nonHttp.push({ code: r.code, label: r.label })
        continue
      }
      const content = bodyContent(doc, effectiveBody(r), r.modelName)
      responses[r.code] = {
        description: r.label || STATUS_BY_CODE.get(r.code)?.meaning || r.code,
        ...(content ? { content } : {}),
        ...(r.isHappyPath ? {} : { 'x-seqflow-unhappy-path': true }),
      }
    }

    if (!Object.keys(responses).length) {
      responses.default = { description: 'No responses modelled yet.' }
    }

    const requestContent = bodyContent(
      doc,
      effectiveBody(contract),
      contract.modelName,
    )
    const operation: Record<string, unknown> = {
      operationId: contract.name,
      summary: describeContract(doc, contract),
      tags: tagsFor(doc, contract),
      ...(parameters.length ? { parameters: stripUndefined(parameters) } : {}),
      ...(requestContent && method !== 'get' && method !== 'delete'
        ? { requestBody: { required: true, content: requestContent } }
        : {}),
      responses,
      ...(nonHttp.length ? { 'x-seqflow-non-http-responses': nonHttp } : {}),
    }

    paths[path][method] = operation
  }

  const spec = {
    openapi: '3.0.3',
    info: {
      title,
      version: '1.0.0',
      description:
        'Generated by SeqFlow from the contracts attached to this sequence diagram. Documentation scaffolding, not a validated API definition.',
    },
    paths,
    components: { schemas: usedSchemas(doc, used) },
  }

  return JSON.stringify(spec, null, 2) + '\n'
}

/* ----------------------------------------------------------------- helpers */

/**
 * The `content` map for a body: the media type comes from the kind, and only
 * structured kinds carry a schema. An opaque kind still needs a schema entry,
 * so it gets the string/binary form OpenAPI expects.
 */
function bodyContent(
  doc: SequenceDoc,
  kind: BodyKind,
  modelName: string | undefined,
): Record<string, { schema: JsonSchema }> | undefined {
  if (kind === 'none') return undefined
  const mediaType = BODY_MEDIA_TYPE[kind]

  if (isStructuredBody(kind)) {
    const schema = schemaRef(doc, modelName)
    if (!schema) return undefined
    return { [mediaType]: { schema } }
  }

  return {
    [mediaType]: {
      schema: kind === 'binary' ? { type: 'string', format: 'binary' } : { type: 'string' },
    },
  }
}

export function usedContracts(doc: SequenceDoc): Contract[] {
  const names = new Set(
    doc.messages.map((m) => m.contractRef).filter((n): n is string => !!n),
  )
  return [...names]
    .map((n) => contractByName(doc, n))
    .filter((c): c is Contract => !!c)
}

function usedSchemas(doc: SequenceDoc, contracts: Contract[]): Record<string, JsonSchema> {
  const all = schemaComponents(doc)
  if (!contracts.length) return {}

  // Keep every model reachable from a used contract, following $refs one level
  // deep is enough because nested fields are inlined rather than referenced.
  const wanted = new Set<string>()
  for (const c of contracts) {
    if (c.modelName) wanted.add(c.modelName)
    for (const r of c.responses) if (r.modelName) wanted.add(r.modelName)
  }

  const out: Record<string, JsonSchema> = {}
  for (const name of wanted) if (all[name]) out[name] = all[name]
  return out
}

function describeContract(doc: SequenceDoc, contract: Contract): string {
  const carriers = doc.messages.filter((m) => m.contractRef === contract.name)
  if (!carriers.length) return contract.name
  const first = carriers[0]
  return `${first.from} → ${first.to}: ${first.label}`
}

function tagsFor(doc: SequenceDoc, contract: Contract): string[] {
  const carriers = doc.messages.filter((m) => m.contractRef === contract.name)
  return [...new Set(carriers.map((m) => m.to))]
}

function stripUndefined<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T
}
