import type { ParticipantKind } from '../../dsl/ast'

/** Human-readable name per kind, used in headings, tooltips and pickers. */
export const KIND_LABEL: Record<ParticipantKind, string> = {
  service: 'Service',
  client: 'Client',
  database: 'Database',
  external: 'External',
  'aws:apigateway': 'API Gateway',
  'aws:lambda': 'Lambda',
  'aws:sqs': 'SQS',
  'aws:sns': 'SNS',
  'aws:eventbridge': 'EventBridge',
  'aws:stepfunctions': 'Step Functions',
  'aws:dynamodb': 'DynamoDB',
  'aws:s3': 'S3',
  'aws:kinesis': 'Kinesis',
  'aws:cognito': 'Cognito',
  'aws:appsync': 'AppSync',
  'aws:ecs': 'ECS',
  'aws:rds': 'RDS',
  'aws:eks': 'EKS',
  'aws:batch': 'Batch',
  'aws:apprunner': 'App Runner',
  'aws:cloudfront': 'CloudFront',
  'aws:waf': 'WAF',
  'aws:msk': 'MSK / Kafka',
  'aws:mq': 'Amazon MQ',
  'aws:aurora': 'Aurora',
  'aws:elasticache': 'ElastiCache',
  'aws:neptune': 'Neptune',
  'aws:redshift': 'Redshift',
  'aws:athena': 'Athena',
  'aws:glue': 'Glue',
  'aws:bedrock': 'Bedrock',
  'aws:bedrockagent': 'Bedrock Agent',
  'aws:knowledgebase': 'Knowledge Base',
  'aws:opensearch': 'OpenSearch',
  'aws:kendra': 'Kendra',
  'aws:sagemaker': 'SageMaker',
  'aws:textract': 'Textract',
  'aws:comprehend': 'Comprehend',
  'aws:rekognition': 'Rekognition',
  'aws:secretsmanager': 'Secrets Manager',
  'aws:kms': 'KMS',
  'aws:cloudwatch': 'CloudWatch',
  'aws:xray': 'X-Ray',
}
